name: replica-core
dependencies:
- certifi=2016.2.28=py35_0
- click=6.7=py35_0
- flask=0.12.2=py35_0
- gunicorn=19.1.0=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.9.6=py35_0
- markupsafe=1.0=py35_0
- openssl=1.0.2l=0
- pastedeploy=1.5.2=py35_1
- pip=9.0.1=py35_1
- python=3.5.4=0
- readline=6.2=2
- requests=2.14.2=py35_0
- setuptools=36.4.0=py35_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- tqdm=4.15.0=py35_0
- werkzeug=0.12.2=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - aniso8601==1.3.0
  - flask-prometheus==0.0.1
  - flask-restplus==0.10.1
  - jsonschema==2.6.0
  - neo4j-driver==1.2.1
  - neomodel==3.2.5
  - prometheus-client==0.0.21
  - pyjwt==1.5.3
  - python-dateutil==2.6.1
  - pytz==2017.3
  - six==1.11.0
  - elasticsearch5==5.5.2
